name: Publish on NuGet/GPR

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: JoeFwd/SafeFluentXPath/.github/workflows/test.yml@main
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish-on-github:

    name: Publish Module on NuGet/GPR
    runs-on: ubuntu-latest
    needs: ["run-tests"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Pack
        run: dotnet pack --configuration Release -o "./packages"
        shell: pwsh
      
      - name: Push to NuGet
        run: dotnet nuget push "./packages/*.nupkg" -k ${{ secrets.NUGET_API_KEY }} -s https://www.nuget.org --skip-duplicate
        shell: pwsh

      - name: Push to GPR
        run: |
          for f in ./packages/*.nupkg
          do
            curl --fail-with-body -vX PUT -u "${{ secrets.PACKAGE_GITHUB_USER }}:${{ secrets.PACKAGE_GITHUB_TOKEN }}"  -F package=@$f https://nuget.pkg.github.com/JoeFwd/
          done
